x-common: &common
  build: .
  volumes:
    - "${PWD}:/app"               # codebase mounted at /app inside container
    - "${PWD}/../data:/data"      # repo-level data directory mounted at /data
  working_dir: /app

services:
  # Re-usable settings for all services (build context, mounts, workdir)
  convert:
    <<: *common
    container_name: dss_converter
    entrypoint: ["python", "python-code/dss_to_csv.py"]

  # Generic service to run csv_levels.py helpers (Level-0 ➜ Level-2, listC, mapBC)
  csv-levels:
    <<: *common
    container_name: csv_levels_helper
    entrypoint: ["python", "python-code/csv_levels.py"]

  validate-sample:
    <<: *common
    container_name: dss_validator_sample
    entrypoint: ["python", "python-code/validate_dss_to_csv.py"]

  validate-all:
    <<: *common
    container_name: dss_validator
    entrypoint: ["python", "python-code/validate_dss_to_csv.py", "--all"]

  # CSV-to-CSV comparison service
  compare-csv:
    <<: *common
    container_name: csv_comparator
    entrypoint: ["python", "python-code/compare_csv_files.py"]



